name: Trigger auto deployment for web-searching-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/web-searching-bot-AutoDeployTrigger-f8dd11b7-85da-4ed5-af4d-070886521b0b.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEBSEARCHINGBOT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.WEBSEARCHINGBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBSEARCHINGBOT_REGISTRY_PASSWORD }}
          containerAppName: web-searching-bot
          resourceGroup: Web-Searching-Bot
          imageToBuild: dro14/web-searching-bot:${{ github.sha }}
          dockerfilePath: Dockerfile

     

